import { build } from "esbuild";
import {
  mkdir,
  readFile,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const packageJson = JSON.parse(
  await readFile(path.join(projectRoot, "package.json"), "utf8"),
);
const dependencyVersions = {
  ...packageJson.peerDependencies,
  ...packageJson.devDependencies,
  ...packageJson.dependencies,
};

function npmSpecifier(bare) {
  const packageName = bare.startsWith("@")
    ? bare.split("/").slice(0, 2).join("/")
    : bare.split("/")[0];
  const subpath = bare.slice(packageName.length);
  const version = dependencyVersions[packageName];
  return version ? `npm:${packageName}@${version}${subpath}` : `npm:${bare}`;
}

const externalizePackages = {
  name: "externalize-packages-as-deno-npm",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /.*/ }, (args) => {
      const specifier = args.path;
      if (
        specifier.startsWith(".") ||
        specifier.startsWith("/") ||
        /^[A-Za-z]:[\\/]/.test(specifier)
      ) {
        return null;
      }
      if (/^(npm|node|jsr|https?|data):/.test(specifier)) {
        return { path: specifier, external: true };
      }
      return { path: npmSpecifier(specifier), external: true };
    });
  },
};

const supabaseConfig = await readFile(
  path.join(projectRoot, "supabase", "config.toml"),
  "utf8",
);
const projectRef =
  process.env.VITE_SUPABASE_PROJECT_ID ??
  supabaseConfig.match(/^\s*project_id\s*=\s*"([^"]+)"/m)?.[1];

if (!projectRef) {
  throw new Error("VITE_SUPABASE_PROJECT_ID/project_id não encontrado.");
}

const wrapper = `
import mcp from "./src/lib/mcp/index.ts";
import { createSupabaseHandler } from "@lovable.dev/mcp-js/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));
`;

const result = await build({
  stdin: {
    contents: wrapper,
    resolveDir: projectRoot,
    sourcefile: "lovable-mcp-supabase-entry.ts",
    loader: "ts",
  },
  bundle: true,
  write: false,
  format: "esm",
  platform: "neutral",
  target: "esnext",
  absWorkingDir: projectRoot,
  logLevel: "info",
  define: {
    "import.meta.env": JSON.stringify({
      MODE: "production",
      DEV: false,
      PROD: true,
      SSR: false,
      VITE_SUPABASE_PROJECT_ID: projectRef,
    }),
    "import.meta.env.VITE_SUPABASE_PROJECT_ID": JSON.stringify(projectRef),
  },
  plugins: [externalizePackages],
});

const output = result.outputFiles?.[0]?.text;
if (!output) throw new Error("O esbuild não gerou a função MCP.");

const banner = `// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// Re-bundled by scripts/build-mcp.mjs to avoid the Windows absolute-path bug in @lovable.dev/mcp-js 0.20.0.
`;
const destinationDir = path.join(projectRoot, "supabase", "functions", "mcp");
const destination = path.join(destinationDir, "index.ts");
await mkdir(destinationDir, { recursive: true });
await writeFile(destination, `${banner}${output}`, "utf8");
console.log(`MCP gerado em ${path.relative(projectRoot, destination)} (${output.length} bytes).`);
