// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-open-receivables.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_receivables_default = defineTool({
  name: "list_open_receivables",
  title: "Listar recebimentos em aberto",
  description: "Lista recebimentos financeiros em aberto (n\xE3o liquidados), opcionalmente filtrando por cliente ou per\xEDodo de vencimento.",
  inputSchema: {
    cliente: z.string().optional().describe("Filtro parcial pelo nome do cliente."),
    vencimento_ate: z.string().optional().describe("Data de vencimento m\xE1xima (YYYY-MM-DD)."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cliente, vencimento_ate, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = client(ctx).from("fin_recebimentos").select(
      "id, gc_codigo, descricao, nome_cliente, valor, data_vencimento, data_emissao, status, os_codigo, nf_numero"
    ).eq("liquidado", false).neq("status", "cancelado").order("data_vencimento", { ascending: true }).limit(limit);
    if (cliente) q = q.ilike("nome_cliente", `%${cliente}%`);
    if (vencimento_ate) q = q.lte("data_vencimento", vencimento_ate);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-open-payables.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_payables_default = defineTool2({
  name: "list_open_payables",
  title: "Listar pagamentos em aberto",
  description: "Lista contas a pagar em aberto (n\xE3o liquidadas), opcionalmente filtrando por fornecedor ou per\xEDodo de vencimento.",
  inputSchema: {
    fornecedor: z2.string().optional().describe("Filtro parcial pelo nome do fornecedor."),
    vencimento_ate: z2.string().optional().describe("Data de vencimento m\xE1xima (YYYY-MM-DD)."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fornecedor, vencimento_ate, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = client2(ctx).from("fin_pagamentos").select(
      "id, gc_codigo, descricao, nome_fornecedor, valor, data_vencimento, data_emissao, status, os_codigo, nf_numero"
    ).eq("liquidado", false).neq("status", "cancelado").order("data_vencimento", { ascending: true }).limit(limit);
    if (fornecedor) q = q.ilike("nome_fornecedor", `%${fornecedor}%`);
    if (vencimento_ate) q = q.lte("data_vencimento", vencimento_ate);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/finance-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var finance_summary_default = defineTool3({
  name: "finance_summary",
  title: "Resumo financeiro",
  description: "Retorna totais em aberto de recebimentos e pagamentos e o saldo previsto (a receber - a pagar).",
  inputSchema: {
    vencimento_ate: z3.string().optional().describe("Considera apenas itens com data de vencimento at\xE9 esta data (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vencimento_ate }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const sb = client3(ctx);
    const sumTable = async (table) => {
      let q = sb.from(table).select("valor").eq("liquidado", false).neq("status", "cancelado");
      if (vencimento_ate) q = q.lte("data_vencimento", vencimento_ate);
      const { data, error } = await q;
      if (error) throw new Error(error.message);
      return (data ?? []).reduce((s, r) => s + Number(r.valor ?? 0), 0);
    };
    try {
      const [aReceber, aPagar] = await Promise.all([
        sumTable("fin_recebimentos"),
        sumTable("fin_pagamentos")
      ]);
      const saldo = aReceber - aPagar;
      const structured = { a_receber: aReceber, a_pagar: aPagar, saldo_previsto: saldo };
      return {
        content: [{ type: "text", text: JSON.stringify(structured) }],
        structuredContent: structured
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: e.message }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "mgiebypxhnmpktljrzjq";
var mcp_default = defineMcp({
  name: "argus-finance-mcp",
  title: "ARGUS Finance OS",
  version: "0.1.0",
  instructions: "Ferramentas somente-leitura sobre o financeiro do ARGUS. Use finance_summary para totais r\xE1pidos, list_open_receivables e list_open_payables para detalhar recebimentos e pagamentos em aberto.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [finance_summary_default, list_open_receivables_default, list_open_payables_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
